apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  labels:
    app: $SERVICE_NAME
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: $SERVICE_NAME
    tier: web
